version: '3'

services:
  ros:
    build: ./
    command: ["tail", "-f", "/dev/random"]
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /dev/dri:/dev/dri










#services:
##  viz:
##    image: osrf/ros:iron-desktop-full
###    container_name: ros_visualizer
##    depends_on:
##      - ros-master
###    networks:
###      - ros
##    environment:
##      - GDK_BACKEND=wayland
##      - "ROS_MASTER_URI=http://ros-master:11311"
##      - DISPLAY=${DISPLAY}
##      - "WAYLAND_DISPLAY=$WAYLAND_DISPLAY"
##      - "XDG_RUNTIME_DIR/$WAYLAND_DISPLAY=/tmp/$WAYLAND_DISPLAY"
###      - "QT_X11_NO_MITSHM=1" #fix some QT bugs
##    #share your user to the container in order to access your x11
##    user: 1000:1000 #adapt as needed!
##    volumes:
##      - /tmp/.X11-unix:/tmp/.X11-unix
###    volumes:
##      #share your x11 socket and permissions to the container
###      - /tmp/.X11-unix:/tmp/.X11-unix:rw
###      - /etc/group:/etc/group:ro
###      - /etc/passwd:/etc/passwd:ro
###      - /etc/shadow:/etc/shadow:ro
###      - /etc/sudoers:/etc/sudoers:ro
###      - /etc/sudoers.d:/etc/sudoers.d:ro
###      - /home/ivan:/home/<your_user>:rw #share your home with write permissions
##    command: rqt
#  ros-master:
#    image: ros:iron-ros-core
#    command: ["tail", "-f", "/dev/random"]
##    command: stdbuf -o L roscore
##    networks:
##      - ros
##    restart: always
#
##  talker:
##    image: ros:iron-ros-core
##    depends_on:
##      - ros-master
##    environment:
##      - "ROS_MASTER_URI=http://ros-master:11311"
##    command: stdbuf -o L rostopic pub /chatter std_msgs/String "hello" -r 1
##    networks:
##      - ros
##    restart: always
##
##  listener:
##    image: ros:iron-ros-core
##    depends_on:
##      - ros-master
##    environment:
##      - "ROS_MASTER_URI=http://ros-master:11311"
##    command: stdbuf -o L rostopic echo /chatter
##    networks:
##      - ros
##    restart: always
#networks:
#  ros:
#    driver: bridge
